### ISSUE TITLE
报错 critical libmamba Shell not initialized

### ISSUE THREAD

**Issue by shijian123** [wy-luke/StableDiffusion-Installer-For-Mac#15]
'micromamba' is running as a subprocess and can't modify the parent shell.
Thus you must initialize your shell before using activate and deactivate.

To initialize the current bash shell, run:
    $ eval "$(micromamba shell hook --shell bash)"
and then activate or deactivate with:
    $ micromamba activate
To automatically initialize all future (bash) shells, run:
    $ micromamba shell init --shell bash --root-prefix=~/micromamba
If your shell was already initialized, reinitialize your shell with:
    $ micromamba shell reinit --shell bash
Otherwise, this may be an issue. In the meantime you can run commands. See:
    $ micromamba run --help

Supported shells are {bash, zsh, csh, xonsh, cmd.exe, powershell, fish}.
critical libmamba Shell not initialized

**Comment by wy-luke** [comment]
确认一下是怎么执行的命令，是按照说明里面的，使用 bash 执行的脚本吗？

**Comment by wy-luke** [comment]
fixed https://github.com/wy-luke/StableDiffusion-Installer-For-Mac/releases/tag/v1.1.0.
