### ISSUE TITLE
请问如果想要第二次使用要什么操作？

### ISSUE THREAD

**Issue by xiaoxue66** [wy-luke/StableDiffusion-Installer-For-Mac#25]
不知道运行什么代码，文件安装在哪里也看不到，没有快捷键

**Comment by xiaoxue66** [comment]
还有怎么安装模型呢。。。

**Comment by wy-luke** [comment]
抱歉哈，这块没有注明。

---

第二次使用的话，有两种办法：
1. 重新执行安装的命令，会自动运行，已经安装的包不会被再次安装，不过时间可能会稍微长一些

2. 执行命令 `bash $HOME/stable-diffusion-webui/webui.sh`，等待片刻，即可运行

---

模型的话，可以从 C 站下载，下载完成后放到 `stable-diffusion-webui/models/Stable-diffusion` 文件夹

C 站：https://civitai.com/

可以参考教程：https://www.uisdc.com/stable-diffusion-3#menu_5

**Comment by xiaoxue66** [comment]
谢谢。请问后续我如果把整个文件夹拷出来到别的位置还能用吗

**Comment by wy-luke** [comment]
可以，只需要把 `bash` 后面的内容替换为你的新路径即可，最后的文件名是一样的，即 `webui.sh`

新运行命令：

`bash /your/path/of/sd/webui.sh`

**Comment by xiaoxue66** [comment]
明白了谢谢

**Comment by xiaoxue66** [comment]
还是要再追问下，为什么我把它拷出去，把user上的那个文件删掉了，运行上面那串代码它又重新在我的user盘里建了一个文件夹

**Comment by wy-luke** [comment]
@xiaoxue66 运行的哪串代码？文件夹里面有内容吗

**Comment by xiaoxue66** [comment]
运行你说的启动代码，就自动在我的user文件夹重新安装，即使我的启动是用的新路径

**Comment by wy-luke** [comment]
@xiaoxue66 如果使用的第一种方法，即安装命令，那就是默认在 HOME 路径安装，这个暂时还不支持更改。

**Comment by xiaoxue66** [comment]
不是安装命令，就是你说的bash /my path..../webui.sh 的命令，也是重新安装

**Comment by wy-luke** [comment]
@xiaoxue66 这个按道理不应该呢 😂
